#Powered by NewsAPI
# Made by Jake Hall

#Imports top headlines from BBC news as a JSON file

import requests
import json

#Returns the JSON file to the function
def get_headline():
    #the request URL
    url = ('https://newsapi.org/v2/top-headlines?sources=bbc-news&apiKey=884b101b64584b2bbb2848f151857de9')

    #response is generated by making a request using requests.get()
    response = requests.get(url)
    #response is deserialised by json()
    data = response.json()
    #full JSON file is returned
    return data
